"""Crear tabla Documentos

Revision ID: 71878f697473
Revises: 800ca0dc7a0c
Create Date: 2026-01-24 11:59:34.990826

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "71878f697473"
down_revision = "800ca0dc7a0c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    def upgrade():
        # 1. CREACIÓN DE LA TABLA DOCUMENTOS (Esto es lo único nuevo que queremos)
        op.create_table(
            "Documentos",
            sa.Column("id", sa.Integer(), nullable=False),
            sa.Column("nombre_original", sa.String(length=255), nullable=False),
            sa.Column("nombre_almacenado", sa.String(length=255), nullable=False),
            sa.Column("ruta_relativa", sa.String(length=500), nullable=False),
            sa.Column("mimetype", sa.String(length=100), nullable=True),
            sa.Column("tamano", sa.Integer(), nullable=True),
            sa.Column("Id_Tiquet", sa.Integer(), nullable=True),
            sa.Column("fecha_creacion", sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(
                ["Id_Tiquet"],
                ["Tiquet.Id_Tiquet"],
            ),
            sa.PrimaryKeyConstraint("id"),
            sa.UniqueConstraint("nombre_almacenado"),
        )

    with op.batch_alter_table("Nivel_de_Satisfaccion", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ID_nivel", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.add_column(sa.Column("Nombre", sa.String(length=255), nullable=True))
        batch_op.drop_column("Id_satisfaccion")
        batch_op.drop_column("nivel")

    with op.batch_alter_table("Permiso", schema=None) as batch_op:
        batch_op.alter_column(
            "Nombre",
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.String(length=255),
            nullable=True,
        )
        batch_op.drop_column("Accion")

    with op.batch_alter_table("Rol", schema=None) as batch_op:
        batch_op.alter_column(
            "Nombre",
            existing_type=mysql.VARCHAR(length=50),
            type_=sa.String(length=255),
            nullable=True,
        )

    with op.batch_alter_table("Rol_Permiso", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("ID_RolPermiso", sa.Integer(), autoincrement=True, nullable=False)
        )
        batch_op.alter_column(
            "ID_Rol", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )
        batch_op.alter_column(
            "ID_Permiso", existing_type=mysql.INTEGER(display_width=11), nullable=True
        )

    with op.batch_alter_table("Ubicaciones", schema=None) as batch_op:
        batch_op.alter_column(
            "Nombre", existing_type=mysql.VARCHAR(length=255), nullable=True
        )
        batch_op.drop_column("Zona")

    with op.batch_alter_table("Usuario", schema=None) as batch_op:
        batch_op.drop_column("Apellido")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Usuario", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("Apellido", mysql.VARCHAR(length=30), nullable=True)
        )

    with op.batch_alter_table("Ubicaciones", schema=None) as batch_op:
        batch_op.add_column(sa.Column("Zona", mysql.VARCHAR(length=255), nullable=True))
        batch_op.alter_column(
            "Nombre", existing_type=mysql.VARCHAR(length=255), nullable=False
        )

    with op.batch_alter_table("Rol_Permiso", schema=None) as batch_op:
        batch_op.alter_column(
            "ID_Permiso", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )
        batch_op.alter_column(
            "ID_Rol", existing_type=mysql.INTEGER(display_width=11), nullable=False
        )
        batch_op.drop_column("ID_RolPermiso")

    with op.batch_alter_table("Rol", schema=None) as batch_op:
        batch_op.alter_column(
            "Nombre",
            existing_type=sa.String(length=255),
            type_=mysql.VARCHAR(length=50),
            nullable=False,
        )

    with op.batch_alter_table("Permiso", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("Accion", mysql.ENUM("U", "D", "I", "R"), nullable=False)
        )
        batch_op.alter_column(
            "Nombre",
            existing_type=sa.String(length=255),
            type_=mysql.VARCHAR(length=50),
            nullable=False,
        )

    with op.batch_alter_table("Nivel_de_Satisfaccion", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("nivel", mysql.VARCHAR(length=255), nullable=True)
        )
        batch_op.add_column(
            sa.Column(
                "Id_satisfaccion",
                mysql.INTEGER(display_width=11),
                autoincrement=True,
                nullable=False,
            )
        )
        batch_op.drop_column("Nombre")
        batch_op.drop_column("ID_nivel")

    with op.batch_alter_table("Log_transaccional", schema=None) as batch_op:
        batch_op.add_column(sa.Column("detalle_cambio", mysql.TEXT(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "ID_log",
                mysql.INTEGER(display_width=11),
                autoincrement=True,
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "usuario",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(
            sa.Column(
                "tiquet",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.add_column(sa.Column("Fecha_cambio", mysql.DATETIME(), nullable=True))
        batch_op.add_column(
            sa.Column(
                "Comentario",
                mysql.INTEGER(display_width=11),
                autoincrement=False,
                nullable=True,
            )
        )
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("Log_transaccional_ibfk_1"), "Tiquet", ["tiquet"], ["Id_Tiquet"]
        )
        batch_op.create_foreign_key(
            batch_op.f("Log_transaccional_ibfk_2"),
            "Comentarios",
            ["Comentario"],
            ["ID_comentario"],
        )
        batch_op.create_foreign_key(
            batch_op.f("Log_transaccional_ibfk_3"),
            "Usuario",
            ["usuario"],
            ["ID_usuario"],
        )
        batch_op.alter_column(
            "Accion",
            existing_type=sa.String(length=255),
            type_=mysql.VARCHAR(length=50),
            existing_nullable=True,
        )
        batch_op.drop_column("Tiquet")
        batch_op.drop_column("Usuario")
        batch_op.drop_column("Id_log")

    # ### end Alembic commands ###
